### ISSUE TITLE
Move to use ESI exclusively

### ISSUE THREAD

**Issue by SpeedProg** [quiescens/eve-ui#1]
CREST inventory/types endpoint is broken now (returns lots of 500) and ccp response was on the lines of "we might look at it, but move to esi"

Would be good to have crest functionality replaced with esi

displaying fits basically doesn't work anymore

**Comment by quiescens** [comment]
I had already looked at using ESI for more things previously but delayed it because there were still things that aren't available on ESI as usual.

**Comment by quiescens** [comment]
Most relevant requests now use ESI as of c20f20655dfe3eb8b6e4346c9b0cf8295b49c89c
