### ISSUE TITLE
Add option to override Accept-Language header

### ISSUE THREAD

**Issue by SpeedProg** [quiescens/eve-ui#3]
Esi is using this header now to localize responses, so fits by default show up in de, hz, jp if the user has this language set in his browser with a higher priority then en-us.

A lot of people seem to be using eve in English through. An option to change the language would be really nice, also maybe language specific caching or idk.
(you can get the used language in the response from content-language header I think)

**Comment by quiescens** [comment]
Ref: https://github.com/quiescens/eve-ui/commit/18bc5f3bb54997bd588e9460debe3d93e6c60a9d
