### ISSUE TITLE
/v4/characters endpoint does not exist

### ISSUE THREAD

**Issue by RedTeaDev** [quiescens/eve-ui#4]
`https://esi.evetech.net/v4/characters/` Endpoint does not exist anymore

![image](https://user-images.githubusercontent.com/51795815/232723044-70b5c55e-7822-4620-9c31-a0410cec0b60.png)

# Fix:
There is a simple solution, change `/v4/characters/` to `/latest/characters/`, for corp and alliances, some value is required for it to show properly

![image](https://user-images.githubusercontent.com/51795815/232723613-3775e0fb-c47d-41a9-bfec-a2f4c328e1fc.png)

**Comment by quiescens** [comment]
Thanks for letting me know @RedTeaDev

I've updated some of the outdated endpoints for now in case anyone is using it as is, but I don't play any more so I don't know when they update things and I'm not actively adding anything new.
